import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
  import "./globals.css";

const reedo = localFont({
  src: [
    {
      path: "../public/fonts/reedo/Reedo-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/reedo/Reedo-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-reedo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${reedo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
